; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S < %s -passes=licm | FileCheck %s

define fastcc void @test(ptr %p) {
; CHECK-LABEL: @test(
; CHECK-NEXT:    br label [[TMP1:%.*]]
; CHECK:       1:
; CHECK-NEXT:    store <vscale x 2 x i64> zeroinitializer, ptr [[P:%.*]], align 2
; CHECK-NEXT:    store i64 0, ptr [[P]], align 2
; CHECK-NEXT:    br label [[TMP1]]
;
  br label %1

1:                                                ; preds = %1, %0
  store <vscale x 2 x i64> zeroinitializer, ptr %p, align 2
  store i64 0, ptr %p, align 2
  br label %1
}


define fastcc void @test2(ptr %p) {
; CHECK-LABEL: @test2(
; CHECK-NEXT:    br label [[TMP1:%.*]]
; CHECK:       1:
; CHECK-NEXT:    br label [[TMP1]]
;
  br label %1

1:                                                ; preds = %1, %0
  store <vscale x 2 x i64> zeroinitializer, ptr %p, align 2
  store <vscale x 2 x i64> zeroinitializer, ptr %p, align 2
  br label %1
}
